packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.66.5
  "@trpc/client": ^11.0.0-rc.772
  "@trpc/tanstack-react-query": ^11.0.0-rc.772
  "@trpc/server": ^11.0.0-rc.772
  eslint: ^9.19.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.14
  typescript: ^5.7.3
  zod: ^3.24.1

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
